import { createRoot } from "react-dom/client";
import { WorkspaceApplication } from "../../../src/renderer/app/WorkspaceApplication";
import { useSettingsStore as settings } from "../../../src/renderer/stores/settings-store";
import { useUiStore as ui } from "../../../src/renderer/stores/ui-store";
import { useInterviewStore as interviews } from "../../../src/renderer/stores/interview-store";
import { useJobLibraryStore as jobs } from "../../../src/renderer/stores/job-library-store";
import { useQuestionBankStore as questions } from "../../../src/renderer/stores/question-bank-store";
import { useAlgorithmPracticeStore as algorithms } from "../../../src/renderer/stores/algorithm-practice-store";
import "../../../src/renderer/lib/theme-bootstrap";
const date="2026-09-26T08:00:00.000Z";
const trace={operationId:"qa-trace",actor:"interviewer",kind:"start",status:"succeeded",startedAt:date,finishedAt:date,durationMs:1000,requestedModel:{providerId:"qa",modelId:"qa"},reasoning:"medium",temperature:0.7,timeoutMs:180000,messages:[{kind:"system_prompt",role:"system",content:"虚构系统提示词，原始信息展示。"},{kind:"history",role:"user",content:'{"message":"保留实际请求原文"}'}],attempts:[{providerId:"qa",modelId:"qa",startedAt:date,finishedAt:date}],outputText:'{"message":"请介绍项目。","questionType":"resume"}'};
const record={id:"qa-interview",title:"后端与 Agent 应用开发面试",candidateName:"测试候选人",positionTitle:"后端开发工程师",status:"interviewing",currentQuestionIndex:1,questionCount:20,competencies:["项目经验","系统设计"],createdAt:date,updatedAt:date,documents:[{id:"r",kind:"resume",content:"测试简历：负责企业知识助手、工具调用和人工确认。"},{id:"j",kind:"job_description",content:"岗位关注服务可靠性与 Agent 工作流。"}]};
const session={interview:record,plan:null,currentQuestion:null,answeredCount:1,preparationError:null,turns:[{id:"q1",ordinal:0,role:"interviewer",questionType:"resume",content:"请介绍你在知识助手项目中负责的一项设计，以及如何验证它的效果。",createdAt:date,trace},{id:"a1",ordinal:1,role:"candidate",content:"我将检索和写操作分开，写入前确认参数，并用固定回放集检查升级后的效果。",createdAt:date}],scoreReports:[]};
const problem={id:1,slug:"two-sum",title:"两数之和",difficulty:"easy",category:"哈希",tags:["数组"],progress:{leetcode:{solved:false,attempts:0},acm:{solved:false,attempts:0}},description:"给定整数数组和目标值，返回两个数的下标。",constraints:["每个输入恰好存在一个答案。"],followUp:"能否在线性时间完成？",leetcode:{className:"Solution",methodName:"twoSum",parameters:[],returnType:"int[]"},acm:{inputFields:[],outputType:"int[]",description:"读取数组与目标值"},examples:[],templates:{leetcode:"class Solution:\n    pass",acm:"print(0)"},drafts:{leetcode:"class Solution:\n    # 编辑草稿保持\n    pass",acm:"print(0)"},answers:[]};
const question={id:"qa-question",stableKey:"qa",version:1,status:"published",title:"如何设计幂等接口？",prompt:"网络重试时如何避免重复执行？",kind:"technical",subtype:"backend",difficulty:"medium",roles:["后端"],seniority:[],competencies:["系统设计"],skills:["幂等性"],estimatedSeconds:120,favorite:false,sourceLabel:"验收样例",updatedAt:date,intent:"验证可靠性设计",answerOutline:["使用稳定的操作标识，保证业务写入与结果记录的一致性。"],rubric:[],commonMistakes:[],followUps:[],source:{id:"qa",type:"manual",title:"验收题库",contentHash:"qa"}};
const info={availableModels:[],model:null};
const bridge={getWindowMaximized:async()=>false,onWindowMaximized:()=>()=>{},getInterviewChatModelInfo:async()=>info,getQuestionPracticeOverview:async()=>({completedSessions:0,practicedQuestions:0,dueReview:0}),getInterviewSession:async()=>session,onJobCollectionProgress:()=>()=>{},getQuestionBankQuestion:async()=>question};
window.piDesktop=new Proxy(bridge,{get(t,k){if(k in t)return t[k as keyof typeof t];throw Error("Unexpected backend call: "+String(k));}}) as any;
settings.setState({theme:"light",palette:"gray",accent:"theme",animationEnabled:false});
ui.setState({activeModule:"interview",moduleViews:{agent:"activity",interview:"dashboard","knowledge-studio":"studio"},detailPanelOpen:true});
interviews.setState({initialized:true,interviews:[record] as any,session:session as any,selectedId:record.id,counts:{draft:0,preparing:0,ready:0,interviewing:1,generating_report:0,completed:0}});
jobs.setState({initialized:true});
questions.setState({initialized:true,snapshot:{total:1,published:1,favorites:0,byKind:{technical:1},byDifficulty:{medium:1},roles:[],skills:[]} as any,items:[question] as any,total:1,selectedId:question.id,detail:question as any});
algorithms.setState({initialized:true,snapshot:{collection:{id:"qa",title:"算法练习",description:"验收样例"},categories:[{name:"哈希",count:1}],problems:[problem],runtime:{available:true,source:"embedded",displayName:"测试 Python"},solved:{leetcode:0,acm:0}},selectedSlug:problem.slug,problem} as any);
(window as any).qa={settings,ui,interviews,jobs,algorithms,session,errors:[]};
window.addEventListener("error",e=>(window as any).qa.errors.push(e.message));
window.addEventListener("unhandledrejection",e=>(window as any).qa.errors.push(String(e.reason)));
createRoot(document.getElementById("root")!).render(<WorkspaceApplication />);
