import {TooltipProvider} from "@radix-ui/react-tooltip";
import {createRoot} from "react-dom/client";
import {useState} from "react";
import {TaskActivityGroup} from "../../src/renderer/features/agent/TaskActivityGroup";
import {useSettingsStore as settings} from "../../src/renderer/stores/settings-store";
import {useUiStore as ui} from "../../src/renderer/stores/ui-store";
import "../../src/renderer/lib/theme-bootstrap";
import {applyTypographySettings} from "../../src/renderer/lib/typography";
document.documentElement.dataset.workspace="agent";
document.body.style.minWidth="0";document.body.style.overflow="auto";
settings.setState({theme:"light",palette:"gray",accent:"theme"});applyTypographySettings(settings.getState());
const applyTheme=()=>{const s=settings.getState();document.documentElement.dataset.theme=s.theme;document.documentElement.dataset.palette=s.palette;document.documentElement.dataset.accent=s.accent;};applyTheme();settings.subscribe(applyTheme);
const message=(id,text)=>({id,role:"assistant",timestamp:1000,streaming:false,content:[{type:"text",contentIndex:0,text}]});
const messages={a:message("a","我先检查页面结构，再统一主题与交互。"),b:message("b","已经找到问题，接下来修改样式，并验证窄窗口显示。"),c:{...message("c",""),content:[{type:"thinking",contentIndex:0,text:"核对布局与参数，确认修改范围。"}]}};
const tool=(id,name,args,output,status="done")=>({id,name,args,output:[{type:"text",text:output}],status,startedAt:1000,completedAt:4000});
const tools={read:tool("read","read",{path:"src/renderer/styles.css"},".sidebar { color: var(--text); }"),shell:tool("shell","bash",{command:"node -e \"" + "console.log(very_long_variable_name);".repeat(50) + "\""},"TypeScript check passed\n".repeat(70)),edit:tool("edit","edit",{path:"src/renderer/styles.css"},"Updated styles"),custom:tool("custom","custom_extension",{query:"example"},"扩展返回的信息"),failed:tool("failed","bash",{command:"npm run verify"},"检查失败：缺少测试配置", "error")};
tools.edit.fileChange={id:"change",path:"src/renderer/styles.css",changeType:"modified",unifiedDiff:"@@ -1 +1 @@\n-color: red;\n+color: var(--text);",truncated:false};
tools.read.output.push({type:"media",mediaType:"image/svg+xml",label:"测试图像",src:"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='40'%3E%3Crect width='80' height='40' fill='gray'/%3E%3C/svg%3E"});
const items=[{type:"assistant",messageId:"a"},{type:"tool",toolId:"read"},{type:"tool",toolId:"shell"},{type:"assistant",messageId:"b"},{type:"tool",toolId:"edit"},{type:"tool",toolId:"custom"},{type:"tool",toolId:"failed"},{type:"final-thinking",messageId:"c"}];
function Demo(){const [state,setState]=useState({tools,settled:true,items});(window as any).qa.update=setState;return <main style={{maxWidth:820,margin:"30px auto",padding:24}}><TaskActivityGroup items={(state.items ?? items) as any} messagesById={messages as any} toolCallsById={state.tools as any} startedAt={1000} endedAt={state.settled?51000:undefined} settled={state.settled}/><p className="assistant-copy">最终回复独立显示：已完成界面调整。</p></main>}
(window as any).qa={settings,ui,errors:[],tools};window.addEventListener("error",e=>(window as any).qa.errors.push(e.message));
createRoot(document.getElementById("root")!).render(<TooltipProvider><Demo/></TooltipProvider>);
