import { createRoot } from "react-dom/client";
import { WorkspaceApplication } from "../../../src/renderer/app/WorkspaceApplication";
import { useSettingsStore as settings } from "../../../src/renderer/stores/settings-store";
import { useUiStore as ui } from "../../../src/renderer/stores/ui-store";
import { useKnowledgeStudioStore as knowledge } from "../../../src/renderer/stores/knowledge-studio-store";
import "../../../src/renderer/lib/theme-bootstrap";
const date = "2026-09-26T08:00:00Z";
const source = {id:"qa-source",title:"Agent 工作流与可靠性设计",kind:"pasted",format:"markdown",contentHash:"qa",charCount:1200,segmentCount:2,createdAt:date,contentPreview:"知识资料",segments:[{id:"s1",ordinal:0,heading:"写入与确认",content:"写入操作应绑定不可变的参数快照，在执行前完成用户确认。",startOffset:0,endOffset:60},{id:"s2",ordinal:1,heading:"幂等与重试",content:"通过稳定的操作标识避免重试产生重复写入。",startOffset:60,endOffset:100}]};
const candidate={id:"q1",batchId:"b1",ordinal:0,kind:"technical",difficulty:"intermediate",competency:"可靠性设计",question:"如何避免工具调用重试导致重复写入？",answer:"通过稳定的操作标识识别同一业务操作，并原子地记录结果。",rubric:[{title:"幂等标识",description:"解释操作标识的稳定性",weight:100}],pitfalls:["仅依赖前端禁用按钮"],followUps:["如何处理并发请求？"],evidence:[{segmentId:"s2",sourceId:source.id,sourceTitle:source.title,quote:source.segments[1].content}],validationStatus:"supported",validationNotes:[],humanStatus:"pending",updatedAt:date};
const batch={id:"b1",title:"Agent 工程能力题目",targetRole:"Agent 应用开发",difficulty:"mixed",requestedQuestionCount:1,sourceIds:[source.id],status:"review",stage:"review",progress:100,candidateCount:1,approvedCount:0,rejectedCount:0,createdAt:date,updatedAt:date,candidates:[candidate],events:[]};
const preview={windowCount:1,coveredSegments:2,availableSegments:2,totalSourceTokens:500,modelContextWindowTokens:32000,fullInputBudgetTokens:22400,requestOverheadTokens:2000,planningReserveTokens:3000,sourceBudgetTokens:17400,windows:[]};
const bridge={getWindowMaximized:async()=>false,onWindowMaximized:()=>()=>{},onKnowledgeGenerationProgress:()=>()=>{},previewKnowledgeBatch:async()=>preview};
window.piDesktop=new Proxy(bridge,{get(t,k){if(k in t)return t[k as keyof typeof t];throw Error("Unexpected backend call: "+String(k));}}) as any;
settings.setState({theme:"light",palette:"gray",accent:"theme",animationEnabled:false});
ui.setState({activeModule:"knowledge-studio",moduleViews:{agent:"activity",interview:"dashboard","knowledge-studio":"studio"}});
const deleted:unknown[]=[];
knowledge.setState({initialized:true,snapshot:{sources:[source],sourceCount:1,batches:[batch],artifactCount:0},sourceDetail:source,selectedSourceId:source.id,batch,selectedBatchId:batch.id,modelInfo:{configured:true,providerId:"qa",modelId:"qa",availableModels:[]},deleteSource:async r=>{deleted.push(r)},deleteBatch:async id=>{deleted.push(id)}} as any);
(window as any).qa={settings,ui,knowledge,deleted,errors:[]};
window.addEventListener("error",e=>(window as any).qa.errors.push(e.message));
window.addEventListener("unhandledrejection",e=>(window as any).qa.errors.push(String(e.reason)));
createRoot(document.getElementById("root")!).render(<WorkspaceApplication />);
