const {app,BrowserWindow,protocol}=require('electron');
const {join,resolve}=require('node:path');
const {writeFileSync}=require('node:fs');
const {createServer}=require('node:http');
const assert=require('node:assert/strict');
const out=resolve(process.argv[2]);
const {registerBrowserIpc,PREVIEW_SCHEME}=require(join(out,'service.cjs'));
protocol.registerSchemesAsPrivileged([{scheme:PREVIEW_SCHEME,privileges:{standard:true,secure:true,supportFetchAPI:true,corsEnabled:true}}]);
app.setPath('userData',join(out,'profile-'+process.pid));
app.on('window-all-closed',()=>{});
let win,server;
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const ui=code=>win.webContents.executeJavaScript(code,true);
const view=()=>win.contentView.children.at(-1);
async function until(check){for(let i=0;i<80;i++){if(await check())return;await pause(100)}throw Error('Timed out waiting for browser')}
app.whenReady().then(async()=>{
 win=new BrowserWindow({width:1100,height:760,show:false,webPreferences:{preload:resolve('tests/e2e/browser-acceptance/preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
 registerBrowserIpc(()=>win,()=>join(out,'site'));
 await win.loadFile(join(out,'index.html'));
 win.showInactive();
 await ui(`document.querySelector('.markdown-link').click()`);
 await until(()=>view()?.webContents.getURL().includes('game.html')&&!view().webContents.isLoading());
 const page=code=>view().webContents.executeJavaScript(code,true);
 assert.equal(await page(`typeof require + '/' + typeof window.piDesktop`),'undefined/undefined');
 await page(`document.querySelector('button').click()`);
 assert.equal(await page(`document.querySelector('#count').textContent`),'1');
 assert.equal(await page(`getComputedStyle(document.body).backgroundColor`),'rgb(240, 245, 250)');
 await pause(300);
 await ui(`window.boundsReads=0;const surface=document.querySelector('.browser-surface');const measure=surface.getBoundingClientRect.bind(surface);surface.getBoundingClientRect=()=>{window.boundsReads++;return measure()};void 0`);
 await pause(400);assert.equal(await ui('window.boundsReads'),0,'idle browser must not poll layout');
 const oldX=view().getBounds().x;
 await ui(`document.querySelector('main').style.gridTemplateColumns='300px minmax(0, 1fr)'`);
 await until(()=>view().getBounds().x!==oldX);
 assert.ok(await ui('window.boundsReads')>0,'layout changes must update browser bounds');
 await ui(`document.querySelector('[aria-label="关闭浏览器"]').click()`);await until(()=>!view().getVisible());
 await ui(`document.querySelector('#reopen').click()`);await until(()=>view().getVisible());
 assert.equal(await page(`document.querySelector('#count').textContent`),'1');
 await ui(`const dialog=document.createElement('div');dialog.id='test-dialog';dialog.setAttribute('aria-modal','true');dialog.textContent='设置';document.body.append(dialog)`);await until(()=>!view().getVisible());
 await ui(`document.querySelector('#test-dialog').remove()`);await until(()=>view().getVisible());
 await ui(`const hiddenDialog=document.createElement('dialog');hiddenDialog.id='hidden-dialog';document.body.append(hiddenDialog);hiddenDialog.showModal()`);await until(()=>!view().getVisible());
 await ui(`document.querySelector('#hidden-dialog').close()`);await until(()=>view().getVisible());
 await ui(`document.querySelector('#hidden-dialog').remove()`);
 await ui(`document.querySelector('[aria-label="刷新"]').click()`);await until(()=>!view().webContents.isLoading());await pause(150);
 assert.equal(await page(`document.querySelector('#count').textContent`),'0');
 await page(`document.querySelector('a').click()`);await until(()=>view().webContents.getURL().includes('next.html')&&!view().webContents.isLoading());
 await until(()=>ui(`!document.querySelector('[aria-label="后退"]').disabled`));
 await ui(`document.querySelector('[aria-label="后退"]').click()`);await until(()=>view().webContents.getURL().includes('game.html')&&!view().webContents.isLoading());
 await until(()=>ui(`!document.querySelector('[aria-label="前进"]').disabled`));
 await ui(`document.querySelector('[aria-label="前进"]').click()`);await until(()=>view().webContents.getURL().includes('next.html')&&!view().webContents.isLoading());
 assert.equal(await page(`fetch('./%2e%2e%5csecret.html').then(r=>r.status)`),403);
 await assert.rejects(()=>ui(`window.piDesktop.browserNavigate('javascript:alert(1)')`));
 server=createServer((_req,res)=>{res.setHeader('Content-Type','text/html');res.end('<title>Localhost preview</title><button onclick="this.textContent=\'works\'">Click</button>')});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 await ui(`window.piDesktop.browserNavigate('http://127.0.0.1:${server.address().port}')`);await until(()=>view().webContents.getTitle()==='Localhost preview'&&!view().webContents.isLoading());
 await page(`document.querySelector('button').click()`);assert.equal(await page(`document.querySelector('button').textContent`),'works');
 await ui(`window.piDesktop.browserNavigate('./game.html')`);await until(()=>view().webContents.getURL().includes('game.html')&&!view().webContents.isLoading());
 for(const [theme,bg,text,panel,border] of [['light','#fff','#202124','#f5f5f5','#ddd'],['dark','#252525','#eee','#303030','#444']]){
  await ui(`document.documentElement.style.cssText='--bg-app:${bg};--text:${text};--text-soft:${text};--text-muted:#888;--bg-panel:${panel};--border:${border};--bg-hover:${border}'`);await pause(100);
  writeFileSync(join(out,theme+'.png'),(await win.webContents.capturePage()).toPNG());
  writeFileSync(join(out,theme+'-page.png'),(await view().webContents.capturePage()).toPNG());
 }
 win.setSize(900,640);await pause(200);const bounds=view().getBounds();const size=win.getContentSize();assert.ok(bounds.x+bounds.width<=size[0]);assert.ok(bounds.y+bounds.height<=size[1]);
 await ui(`document.querySelector('#chinese-link a').click()`);
 await until(()=>view().webContents.getTitle()==='中文路径验证'&&!view().webContents.isLoading());
 assert.equal(await page(`document.body.dataset.loaded`),'成功');
 await page(`document.querySelector('button').click()`);
 assert.equal(await page(`document.querySelector('button').textContent`),'成功');
 const contents=view().webContents;win.destroy();await until(()=>contents.isDestroyed());
 server.close();console.log('PASS: HTML links, script/CSS, game interaction, hide/reopen, modal occlusion, reload, history, localhost, isolation, path boundary and disposal');app.exit(0);
}).catch(error=>{console.error(error);server?.close();app.exit(1)});


