PROBLEM = {
    "id": 3,
    "title": "无重复字符的最长子串",
    "slug": "longest_substring_without_repeating_characters",
    "difficulty": "medium",
    "tags": ["字符串", "滑动窗口"],
    "description": "给定一个字符串 s ，请你找出其中不含有重复字符的 最长子串 的长度。",
    "examples": [
        {"input": {"s": "abcabcbb"}, "output": 3,
         "explanation": "因为无重复字符的最长子串是 \"abc\"，所以其长度为 3。"},
        {"input": {"s": "bbbbb"}, "output": 1,
         "explanation": "因为无重复字符的最长子串是 \"b\"，所以其长度为 1。"},
        {"input": {"s": "pwwkew"}, "output": 3,
         "explanation": "因为无重复字符的最长子串是 \"wke\"，所以其长度为 3。请注意，你的答案必须是 子串 的长度，\"pwke\" 是一个子序列，不是子串。"},
    ],
    "constraints": [
        "0 <= s.length <= 5 * 10^4",
        "s 由英文字母、数字、符号和空格组成",
    ],
    "leetcode": {
        "class": "Solution",
        "method": "lengthOfLongestSubstring",
        "params": [("s", "str")],
        "return": "int",
    },
    "acm": {
        "input_fields": [("s", "str")],
        "output_type": "int",
        "description": "输入一行字符串 s。输出无重复字符的最长子串长度。",
    },
    "test_cases": [
        {"input": {"s": "abcabcbb"}, "output": 3},
        {"input": {"s": "bbbbb"}, "output": 1},
        {"input": {"s": "pwwkew"}, "output": 3},
        {"input": {"s": ""}, "output": 0},
        {"input": {"s": " "}, "output": 1},
        {"input": {"s": "au"}, "output": 2},
        {"input": {"s": "dvdf"}, "output": 3},
    ],
}
